name: PR Build Website

on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "blog/**"
      - "website/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'website skip')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Prettier & Build
        run: |
          cd website
          yarn install && yarn prettier
          git config --global user.name 'GitHub Action'
          git config --global user.email 'github-action@users.noreply.github.com'
          git commit -am "Prettier"
          git push
          yarn build